# Generated by Django 5.2.8 on 2025-11-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attrezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_civico', models.CharField(blank=True, max_length=10, null=True)),
                ('citta', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=10, null=True)),
                ('data_inizio_iscrizioni', models.DateField(blank=True, null=True)),
                ('data_fine_iscrizioni', models.DateField(blank=True, null=True)),
                ('data_termine_pagamento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Societa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codice_fiscale', models.CharField(max_length=100, unique=True)),
                ('indirizzo', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_civico', models.CharField(blank=True, max_length=10, null=True)),
                ('citta', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('partita_iva', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('anno_nascita', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.categoria')),
                ('livello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.livello')),
                ('societa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.societa')),
            ],
        ),
    ]
