# Generated by Django 5.2.8 on 2025-11-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atleta',
            options={'verbose_name': 'Atleta', 'verbose_name_plural': 'Atleti'},
        ),
        migrations.AlterModelOptions(
            name='attrezzo',
            options={'verbose_name': 'Attrezzo', 'verbose_name_plural': 'Attrezzi'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='competizione',
            options={'verbose_name': 'Competizione', 'verbose_name_plural': 'Competizioni'},
        ),
        migrations.AlterModelOptions(
            name='livello',
            options={'verbose_name': 'Livello', 'verbose_name_plural': 'Livelli'},
        ),
        migrations.AlterModelOptions(
            name='societa',
            options={'verbose_name': 'Società', 'verbose_name_plural': 'Società'},
        ),
    ]
