# Generated by Django 5.2.8 on 2025-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0002_alter_atleta_options_alter_attrezzo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fascia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fascia',
                'verbose_name_plural': 'Fasce',
            },
        ),
    ]
