# Generated by Django 5.2.8 on 2025-11-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_fascia'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='fascia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.fascia'),
        ),
    ]
